service: sls-off-mdnsr
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128
  stage: dev
  httpApi:
    cors: false
  layers:
    # Gotta Deploy via AWS Console first, when copy the Version ARN into here:
    - arn:aws:lambda:us-east-1:684482388085:layer:canvas-nodejs:3
  environment:
    LD_PRELOAD: /var/task/node_modules/canvas/build/Release/libz.so.1
functions:
  hello:
    handler: index.hello
    events:
      - httpApi:
          path: /hello
          method: GET
  time:
    handler: index.time
    events:
      - httpApi:
          path: /time
          method: GET
plugins:
  - serverless-offline
